apiVersion: v1
kind: Pod
metadata:
  name: k8s-debugging-pod
  namespace: default
spec:
  containers:
  - name: k8s-debugging-pod-1
    image: pchahal24/k8s-debugging-pod:latest
    command:
    - "sleep"
    - "31536000"
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
